# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    container_name: mysqldb
    cap_add:
      - SYS_NICE
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: todos
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./docker/db:/var/lib/mysql
volumes:
  db:
    driver: local